name: Send Weekly Prayer Intentions

on:
  schedule:
    - cron: '0 15 * * 0' # Every Sunday at 15:00 UTC (8 AM California time during DST)
  workflow_dispatch:

jobs:
  send-intentions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./stcarloacutis.net

      - name: Run sendIntentions script
        env:
          NODE_PATH: ${{ github.workspace }}/stcarloacutis.net/node_modules
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: ../stcarloacutis.net/node_modules/.bin/ts-node --compiler-options '{"module":"CommonJS"}' scripts/sendIntentions.ts
        working-directory: .